
INSERT INTO `zones` (`zone_country_id`, `zone_name`, `zone_code`) VALUES 
(84, 'Achaea', 'AC'),
( 84, 'Aitolia - Acarnania', 'AI'),
( 84, 'Arcadia', 'AR'),
( 84, 'Argolis', 'ARG'),
( 84, 'Arta', 'ART'),
( 84, 'Athens', 'ATH'),
( 84, 'Boeotia', 'BO'),
( 84, 'Chalcidice', 'CH'),
( 84, 'Chania', 'CHA'),
( 84, 'Chios', 'CHI'),
( 84, 'Corfu', 'CO'),
( 84, 'Corinthia', 'COR'),
( 84, 'Cyclades', 'CY'),
( 84, 'Dodecanese', 'DO'),
( 84, 'Drama', 'DR'),
( 84, 'East Attica', 'EA'),
( 84, 'Elis', 'EL'),
( 84, 'Euboea', 'EU'),
( 84, 'Evros', 'EV'),
( 84, 'Evrytania', 'EVR'),
( 84, 'Florina', 'FL'),
( 84, 'Grevena', 'GR'),
( 84, 'Heraklion', 'HE'),
( 84, 'Imathia', 'IM'),
( 84, 'Ioannina', 'IO'),
( 84, 'Karditsa', 'KA'),
( 84, 'Kastoria', 'KAS'),
( 84, 'Kavala', 'KAV'),
( 84, 'Kefalonia', 'KE'),
( 84, 'Kilkis', 'KI'),
( 84, 'Kozani', 'KO'),
( 84, 'Laconia', 'LA'),
( 84, 'Larissa', 'LAR'),
( 84, 'Lasithi', 'LAS'),
( 84, 'Lefkada', 'LE'),
( 84, 'Lesbos', 'LES'),
( 84, 'Magnesia', 'MA'),
( 84, 'Messinia', 'ME'),
( 84, 'Pella', 'PE'),
( 84, 'Phocis', 'PH'),
( 84, 'Phthiotis', 'PHT'),
( 84, 'Pieria', 'PI'),
( 84, 'Piraeus', 'PIR'),
( 84, 'Preveza', 'PR'),
( 84, 'Rethymno', 'RE'),
( 84, 'Rhodope', 'RH'),
( 84, 'Samos', 'SA'),
( 84, 'Serres', 'SE'),
( 84, 'Thesprotia', 'TH'),
( 84, 'Thessaloniki', 'THE'),
( 84, 'Trikala', 'TR'),
( 84, 'West Attica', 'WA'),
( 84, 'Xanthi', 'XA'),
( 84, 'Zakynthos', 'ZA');
